plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "coverage/**/*"
    - "pkg/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NamedSubject:
  Enabled: false
